### ISSUE TITLE
when i am clicking the translate button the  text is not transalated . please help bro.

### ISSUE THREAD

**Issue by manishkaushik2314** [RahulRoy-rsp/Language_Translator#1]
working but the  main thing the translation is not doing . where to make changes in the code . my social media is @who_thekaushik in instagm
![Screenshot (12)](https://user-images.githubusercontent.com/108325609/176115955-ce7bf4ac-139d-4516-b84c-379747eeac54.png)

**Comment by RahulRoy-rsp** [comment]
Can you show me the error that you are facing?
